version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.2
    - 0.1101.3
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: firebase-tools
    versions:
    - 9.2.2
    - 9.3.0
    - 9.4.0
    - 9.5.0
    - 9.6.0
    - 9.6.1
    - 9.7.0
    - 9.8.0
    - 9.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: firebaseui
    versions:
    - 4.7.3
  - dependency-name: zone.js
    versions:
    - 0.11.3
  - dependency-name: ngx-cookie
    versions:
    - 5.0.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: replace-in-file
    versions:
    - 6.1.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
  - dependency-name: "@cloudinary/angular-5.x"
    versions:
    - 1.3.4
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
  - dependency-name: "@angular/fire"
    versions:
    - 6.1.4
  - dependency-name: inquirer
    versions:
    - 7.3.3
  - dependency-name: protractor
    versions:
    - 7.0.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
